### ISSUE TITLE
Delete does not set deletedAt

### ISSUE THREAD

**Issue by raymondbutcher** [internalfx/regrid#14]
The [spec](https://github.com/internalfx/regrid-spec) mentions a `deletedAt` field but it's not being set by the `delete()` function.

**Comment by internalfx** [comment]
@bchavez I have started setting the `deletedAt` date in master.

Are you currently doing that as well?

**Comment by bchavez** [comment]
Hey @internalfx, thanks for the heads up.

Yeah, I've already been setting the `deletedAt` date in the C# driver:
https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver.ReGrid/FileSystemMethods.cs#L186
