### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by chrisabrams** [internalfx/regrid#6]
This looks like a pretty awesome project. Is there a built in test to measure performance of files?

**Comment by internalfx** [comment]
No built in test....but....

One of the reasons I developed this was to be able to synchronize tables with binary data quickly.

For instance, one of my clients has a 20GB database with binary data. Getting a new copy of this database for local development is inconvenient to say the least.

Thinker can synchronize the database over the internet in under 20 mins (It only copies whats actually different). :smile:

**Comment by internalfx** [comment]
There is no built-in test.

But there is a separate repo I use for performance testing.

https://github.com/internalfx/regrid-benchmark

On my modest laptop (with SSD) I get about 40MB/sec read and write.

**Comment by chrisabrams** [comment]
Thanks; I'll check that out. It's nice to know that thinker only diffs - I didn't catch that on its readme

**Comment by internalfx** [comment]
> I didn't catch that on its readme 

@chrisabrams I didn't write it....my bad...fixed
