### ISSUE TITLE
Horizon support 

### ISSUE THREAD

**Issue by lavvy** [internalfx/regrid#7]
Hey @internalfx  i am just thinking the horizon project might be nice if we could use it with regrid. 
Have you tried seeing how you could integrate regrid with horizon. And horizon is backed by rethinkdb,  i think   one of the important  solutions still missing in it is regrid. 
Could you take a look and see if it could integrate seamlessly. https://github.com/rethinkdb/horizon

Secondly, what about supporting some of rethinkdb supported api languages like javascript and python, and php could be really nice too.

**Comment by internalfx** [comment]
I have not looked much at Horizon, but after skimming their site....

Horizon appears to be a more standardized replacement for what I have been building myself for many projects now.

It is an application server.

ReGrid is a library for file storage.

It is up to the builder of the application server to choose whether or not to use it.

Horizon having an integration with ReGrid would mean changes to Horizon, not ReGrid. It blindly stores whatever it is told to. And does not care who, or what, is using it.

I think the Horizon project is probably where you want to ask this question.
