### ISSUE TITLE
Fuse mount for regrid 

### ISSUE THREAD

**Issue by lavvy** [internalfx/regrid#8]
Hey @internalfx please how possible is to add a fuse mountable point in regrid. 
Going through this issue https://github.com/rethinkdb/rethinkdb/issues/2647  . I think there is a possibility of making rethinkdb mountable as fuse filesystem.  Please can you add a fuse mount point to it. We are not familiar with nodejs and c-sharp which are the two drivers available now for regrid . But i think with fuse it would be more easier and will adapt to most applications

**Comment by internalfx** [comment]
@lavvy A regrid fuse driver is an interesting idea, but there are some issues.

1. Regrid does not follow the same "rules" as a traditional filesystem
2. A fuse driver is not currently something I can dedicate time to.
