### ISSUE TITLE
Thumbnails?

### ISSUE THREAD

**Issue by wmertens** [internalfx/regrid#9]
What would be the best way to implement thumbnails? Basically they are derived data that can be created lazily on first read, but then cached.
How to ensure the thumbnail cache remains current, removing the thumbnail on file update or removal? Should there be a cache invalidator that listens to all file changes?

**Comment by internalfx** [comment]
The `watch` methods should give you what you need.

**Comment by wmertens** [comment]
So I'll take that as, yes, use a listener :)

**Comment by internalfx** [comment]
It's really completely up to you how you prefer to handle it.

Regrid is not opinionated on something like this.

**Comment by wmertens** [comment]
Right, I understand, I was rather hoping that someone already did something like this and had insights. But using `watch` seems straightforward enough…
